name: anshin
version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  serverless-redis-http:
    image: hiett/serverless-redis-http:latest
    ports:
      - '8079:80'
    environment:
      SRH_MODE: env
      SRH_TOKEN: ${SRH_TOKEN}
      SRH_CONNECTION_STRING: 'redis://redis:6379'
  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - '5540:5540'
    volumes:
      - redisinsight-data:/data
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: user
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: anshin
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  redisinsight-data:
  mysql-data:
