import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { validateRequest } from '@/lib/auth';
import { Analytics } from '@/components/Analytics';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user, cart } = await validateRequest();

  return (
    <html lang="en">
      <Analytics />
      <body className={inter.className}>
        <Header user={user} cart={cart} />
        <div className="flex flex-col items-center justify-center">
          {children}
        </div>
        <div className="py-12" />
        <Footer />
      </body>
    </html>
  );
}

const Footer = () => {
  const currentYear = new Date().getFullYear();
  return (
    <footer className="flex min-h-20 w-full flex-col items-center justify-center bg-card p-4">
      <span className="flex flex-col items-center">
        <span>Made with ❤️</span>
        <Link href="https://kyrre.dev" className="hover:underline">
          Kyrre Gjerstad
        </Link>
        Anshin &copy; {currentYear}
      </span>
    </footer>
  );
};
