import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { validateRequest } from '@/lib/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user, guest } = await validateRequest();

  console.log(user);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header user={user} guest={guest} />
        {children}
      </body>
    </html>
  );
}
