import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { validateRequest } from '@/lib/auth';
import { Analytics } from '@/components/Analytics';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user, cart } = await validateRequest();

  return (
    <html lang="en">
      <Analytics />
      <body className={inter.className}>
        <Header user={user} cart={cart} />
        <div className="flex flex-col items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
